version: "3"

services:
  app:
    build: ./docker/elixir
    ports:
      - ${APP_PORT}:4000

  db:
    build: ./docker/postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432